### ISSUE TITLE
bounding box detection is based on grid origin which could be out of bounds

### ISSUE THREAD

**Issue by StalkR** [Casimir255/QuantumHangar-EOL-#59]
Digging bug report from a user, which actually reveals an issue with the bounding box code:

- build a grid
- extend it to one side with many blocks
- then build something at the end
- and remove all the blocks from the origin, keeping only the end

The bounding box is somehow still centered on that grid origin, when it should in fact be more or less at the center of the grid.

This might be a known keen bug for keeping the grid origin outside of the actual grid, but maybe we can work around it by calculating the real center of blocks.

https://github.com/Casimir255/QuantumHangar/blob/master/Utilities/ParallelSpawner.cs#L244

**Comment by Casimir255** [comment]
@StalkR Two years later, I found the issue and the grid box should be working as expected now. This was fixed back in Jan

**Comment by StalkR** [comment]
Well done! cheers :)
