### ISSUE TITLE
Need List of .cfg options

### ISSUE THREAD

**Issue by Krocodile13** [Casimir255/QuantumHangar-EOL-#66]
Hi there, I use Server Blend for hosting my SE server specifically but i think its the same for all rented servers where you don't get access to the torch panel. I have to edit the actual config file itself. Not too bad but the documentation for the plugin doesnt include what the written options in the config are. For example in <LoadType>ForceLoadMearPlayer</LoadType> I want to set it to the option of having grids spawn where they were saved but I don't know what the written code for that is and thus can't edit this. If you could provide the written options for the config that would be awesome. 

Thanks

**Comment by buttheadbob** [comment]
You could always install torch locally and set it up how you want the server to run. Than you can copy that configuration directly without miscommunication or other possible mistakes.

**Comment by Casimir255** [comment]
I would always recommend people use a local install of torch to setup any plugin configs. Most plugins have a UI that makes config setup easy
